apiVersion: v1
kind: Pod
metadata:
  name: netcat-server
spec:
  nodeName: p3768-0000-p3767-0001
  containers:
    - name: nc-server
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - while true; do echo "Hello from Edge Node" | nc -l -p 12345; done
      securityContext:
        capabilities:
          add: ["NET_RAW"]
      ports:
        - containerPort: 12345

---
apiVersion: v1
kind: Pod
metadata:
  name: netcat-client
spec:
  nodeName: master1
  containers:
    - name: nc-client
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 3600; done"]
